### ISSUE TITLE
test_abbreviated_annotations fails

### ISSUE THREAD

**Issue by opoplawski** [enthought/traits#1073]
Running tests for 6.0.0 on Fedora Rawhide:
```
+ pushd build/lib.linux-x86_64-3.8
~/fedora/python-Traits/traits-6.0.0/build/lib.linux-x86_64-3.8 ~/fedora/python-Traits/traits-6.0.0
+ xvfb-run /usr/bin/python3 -m unittest discover -v
ERROR: test_abbreviated_annotations (traits.util.tests.test_trait_documenter.TestTraitDocumenter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/orion/fedora/python-Traits/traits-6.0.0/build/lib.linux-x86_64-3.8/traits/util/tests/test_trait_documenter.py", line 116, in test_abbreviated_annotations
    with self.create_directive() as directive:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/orion/fedora/python-Traits/traits-6.0.0/build/lib.linux-x86_64-3.8/traits/util/tests/test_trait_documenter.py", line 166, in create_directive
    app.env, LoggingReporter(''), Options(), 1, **kwds)
TypeError: __init__() missing 2 required positional arguments: 'report_level' and 'halt_level'
```
This doesn't make any sense to me.  Using sphinx 2.2.2.

**Comment by opoplawski** [comment]
Sorry, this was user error.  Apparently I had a user-local install on sphinx that was triggering this.  Hard to detect since it wasn't in the backtrace.
