### ISSUE TITLE
Reference leaks in test_expression

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1145]
When running with a debug build of Python (specifically, this was Python 3.9b0), I'm seeing object reference leaks from `test_expression`.

```
test_expression leaked [44, 44, 44, 44] references, sum=176
test_expression leaked [12, 12, 12, 12] memory blocks, sum=48
0:00:23 load avg: 2.36 [28/90/2] test_extended_notifiers -- test_expression failed
```

Note: since this was with a Python pre-release, the first thing we should do it retest with a released version of Python, just in case: this could conceivably be a core Python bug (unlikely, but possible).

See #725 for steps to run a reference leak test.

**Comment by mdickinson** [comment]
Reproduced this with Python 3.8.3 built from source. So it's unlikely to be a core Python bug.

I also see some very strange failures from the refleak test run, presumably resulting from running the relevant tests multiple times:

```
======================================================================
FAIL: test_dict_event_repr (test_trait_dict_list_set_event.TestTraitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_trait_dict_list_set_event.py", line 53, in test_dict_event_repr
    self.assertEqual(event.__repr__(), event_str)
AssertionError: "TraitDictEvent(removed={}, added={}, changed={'blue': 10, 'black': 0})" != "TraitDictEvent(removed={}, added={'black': 0}, changed={'blue': 0})"
- TraitDictEvent(removed={}, added={}, changed={'blue': 10, 'black': 0})
?                                                       -------------
+ TraitDictEvent(removed={}, added={'black': 0}, changed={'blue': 0})
?                                   ++++++++++


======================================================================
FAIL: test_list_repr (test_trait_dict_list_set_event.TestTraitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_trait_dict_list_set_event.py", line 41, in test_list_repr
    self.assertEqual(event.__repr__(), event_str)
AssertionError: 'TraitListEvent(index=slice(0, 3, 2), removed=[4, 5], added=[4, 5])' != 'TraitListEvent(index=slice(0, 3, 2), removed=[1, 3], added=[4, 5])'
- TraitListEvent(index=slice(0, 3, 2), removed=[4, 5], added=[4, 5])
?                                               ^  ^
+ TraitListEvent(index=slice(0, 3, 2), removed=[1, 3], added=[4, 5])
?                                               ^  ^


======================================================================
FAIL: test_set_event_repr (test_trait_dict_list_set_event.TestTraitEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_trait_dict_list_set_event.py", line 64, in test_set_event_repr
    self.assertEqual(event.__repr__(), event_str)
AssertionError: 'TraitSetEvent(removed={4}, added={3})' != 'TraitSetEvent(removed={3}, added={4})'
- TraitSetEvent(removed={4}, added={3})
?                        ^          ^
+ TraitSetEvent(removed={3}, added={4})
?                        ^          ^
```

**Comment by mdickinson** [comment]
> I also see some very strange failures [...]

Okay, now that I look at the code it's not so strange; fix on the way. (But the refleak is still present.)

**Comment by mdickinson** [comment]
Here's a minimal reproducer for the reference leak. It needs a debug build of Python (for the `sys.gettotalrefcount` function).

```python
import sys

from traits.api import Expression, HasTraits


class Foo(HasTraits):
    bar = Expression()

    def _bar_default(self):
        return "1"


def show_ref_count():
    for _ in range(10):
        Foo().bar
        print(f"Total ref count: {sys.gettotalrefcount()}")


if __name__ == "__main__":
    show_ref_count()
```

Output on my machine:
```
(traits-pydebug) mirzakhani:traits mdickinson$ python temp/test_expression2.py 
Total ref count: 175099
Total ref count: 175112
Total ref count: 175123
Total ref count: 175134
Total ref count: 175145
Total ref count: 175156
Total ref count: 175167
Total ref count: 175178
Total ref count: 175189
Total ref count: 175200
```
