### ISSUE TITLE
PrefixList validation tracebacks are chained

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1155]
Validation exceptions from assignment to a `PrefixList` trait have some unnecessary nesting; this is going to clutter logs and consoles. It would be good to get rid of this.

This is probably not specific to `PrefixList`.

```python
>>> from traits.api import HasTraits, PrefixList
>>> class A(HasTraits):
...     foo = PrefixList(["yes", "no"])
... 
>>> a = A()
>>> a.foo = "bogus"
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_type.py", line 355, in _value_for
    return self.value_for(value)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_types.py", line 2629, in value_for
    raise TraitError(
traits.trait_errors.TraitError: The value of a PrefixList trait must be 'yes' or 'no' (or any unique prefix), but a value of 'bogus' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_type.py", line 357, in _value_for
    self.error(object, name, value)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'foo' trait of an A instance must be 'yes' or 'no' (or any unique prefix), but a value of 'bogus' <class 'str'> was specified.
```

Assigning to the 6.1 milestone to see if there's anything we can reasonably do about this before the release. If not, it can be bumped.

**Comment by kitchoi** [comment]
One way to fix is to do `raise ... from None` in 
https://github.com/enthought/traits/blob/94a3dca59c51a2a89329a539f351cc878efb2d06/traits/base_trait_handler.py#L57-L76

But this is perhaps too general and removed from the context where the exception came from. There are probably situations where the chained traceback is helpful. We could add a flag in `BaseTraitHandler.error` to optionally `raise ... from None` I suppose. Does this worth the extra code branch?

**Comment by mdickinson** [comment]
Bumping to 6.2.0

**Comment by mdickinson** [comment]
"Fixed" in #1563 for `PrefixList` and `PrefixMap`, by replacing their use of `value_for` with plain old `validate`.

More generally, any `TraitType` subclass that uses the `value_for` method for its validation will have this issue. `PrefixList` and `PrefixMap` are the only `TraitType` subclasses in the current main branch that use `value_for`. Given that the symptoms are mild and that the prevalence of the issue seems tiny, it doesn't seem worth fixing this more generally.

Relevant code:

- https://github.com/enthought/traits/blob/0e74444a5000c5813a02aa0b30549887ff12645b/traits/trait_type.py#L155-L161
- https://github.com/enthought/traits/blob/0e74444a5000c5813a02aa0b30549887ff12645b/traits/trait_type.py#L402-L404
