### ISSUE TITLE
TraitListObject._validate_length should not be called for non-length-constrained lists

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1171]
We're currently calling `TraitListObject._validate_length` for non-length-constrained lists, and we shouldn't be.

This is likely due to using a default minimum length of `0` rather than `None` somewhere.

**Comment by mdickinson** [comment]
Example:
```
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = List(Int)
... 
>>> a = A()
>>> a.foo.remove(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 800, in remove
    self._validate_length(len(self) - 1)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 887, in _validate_length
    raise TraitError(
traits.trait_errors.TraitError: The 'foo' trait of a type instance must be a list of items which are an integer, but you attempted to change its length to -1 elements.
```

With Traits 6.0.0, the same example gives:
```
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = List(Int)
... 
>>> a = A()
>>> a.foo.remove(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 405, in remove
    list.remove(self, value)
ValueError: list.remove(x): x not in list
```
