### ISSUE TITLE
Discourage uses of the Function trait type

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1215]
The [`Function` trait type](https://github.com/enthought/traits/blob/24c4d76d688f8a86f83dd80b6ffd7a1226b27ebc/traits/trait_types.py#L915-L923) is almost never what you actually want: it checks specifically for an instance of `<class 'function'>` (a.k.a. `types.FunctionType`). That includes Python functions defined with `def` and lambda functions, but does not include built-in functions, functions defined in Cython or C code, instances of some other class that supplies `__call__`.

This makes `Function` something of a bug magnet. On the (presumably) rare occasions that someone genuinely needs an instance specifically of type `types.FunctionType`, they can use `Instance(types.FunctionType)`.

In most cases, a user is likely to want `Callable` instead.

I'm not sure whether we want to go as far as deprecating `Function`, but we could at least indicate in its docstring that it's probably not actually what you want.

**Comment by mdickinson** [comment]
Just one example of where a use of `Function` could be problematic: if we Cythonize a Python file (for whatever reason: optimization, obfuscation) and the original Python file supplies a function for a `Function` trait, the Cythonized version of the function will no longer be accepted.

**Comment by mdickinson** [comment]
I'm more-or-less convinced myself that we _should_ deprecate `Function` at this point. Probably start with a soft deprecation (documented as deprecated, but no deprecation warning) and see how much pain that causes, if any.

**Comment by mdickinson** [comment]
There's also a `Method` trait type, which has similar issues - it's a non-duck-typed `isinstance` check. There probably _are_ use-cases for checking for a bound method, but `Method` doesn't currently do that. We may want to fix `Method` up to be more duck-typed.

**Comment by mdickinson** [comment]
As another example of how something that you'd _think_ would qualify as a `Function` fails validation:

```
mdickinson@mirzakhani ~ % python
Python 3.9.1 (default, Dec  8 2020, 11:42:15) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from functools import lru_cache
>>> @lru_cache(100)
... def f(n):
...     return n * n
... 
>>> type(f)
<class 'functools._lru_cache_wrapper'>
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = Function()
... 
>>> a = A()
>>> a.foo = f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Library/Python/3.9/lib/python/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'foo' trait of an A instance must be a function, but a value of <functools._lru_cache_wrapper object at 0x10a3caa40> <class 'functools._lru_cache_wrapper'> was specified.
```

```
>>> from functools import lru_cache
>>> @lru_cache(100)
... def f(n):
...     return n * n
... 
>>> type(f)
<class 'functools._lru_cache_wrapper'>
```
