### ISSUE TITLE
test_enum fails if Pyface is installed but TraitsUI is not.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1266]
The tests in `test_enum.py` fail if Pyface is installed but TraitsUI is not. If that's fixed, it fails in a different way when Pyface is installed but Pyside2 (or PyQt5) is not.

```
mirzakhani:traits mdickinson$ python -m venv --clear ~/.venvs/traits
mirzakhani:traits mdickinson$ source ~/.venvs/traits/bin/activate
(traits) mirzakhani:traits mdickinson$ pip install -q --upgrade pip setuptools wheel
(traits) mirzakhani:traits mdickinson$ pip install -q pyface pyside2
(traits) mirzakhani:traits mdickinson$ pip install -q -e .
(traits) mirzakhani:traits mdickinson$ python -m unittest -f
........................................................................................................................................................................................................................................................................................................................................................ssssssssssss...s..sss.............................ssssss...............................................................................................................ssssssss............................................ssssssssssssssssE
======================================================================
ERROR: traits.tests.test_enum (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: traits.tests.test_enum
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_enum.py", line 19, in <module>
    GuiTestAssistant = pyface.toolkit.toolkit_object(
AttributeError: module 'pyface' has no attribute 'toolkit'


----------------------------------------------------------------------
Ran 580 tests in 7.428s

FAILED (errors=1, skipped=46)
```

**Comment by mdickinson** [comment]
This should be a relatively easy fix for the next milestone.
