### ISSUE TITLE
Equality testing issue in traits.observation

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1277]
The following code:
```
import numpy
from traits.api import HasTraits, ComparisonMode, Array, List, Union, observe
from traits.observation.api import trait

class Example(HasTraits):

    list_or_array = Union(List, Array, comparison_mode=ComparisonMode.identity)

    @observe(trait("list_or_array").list_items(optional=True))
    def something_changed(self, event):
        print(event)

example = Example()
example.list_or_array = [1, 2, 3, 4, 5]
example.list_or_array.append(5)
example.list_or_array = numpy.array([1, 2, 3, 4, 5])
```
fails on the last line with the following output
```
TraitChangeEvent(object=<__main__.Example object at 0x10190eaf0>, name='list_or_array', old=None, new=[1, 2, 3, 4, 5])
ListChangeEvent(object=[1, 2, 3, 4, 5, 5], index=5, removed=[], added=[5])
TraitChangeEvent(object=<__main__.Example object at 0x10190eaf0>, name='list_or_array', old=[1, 2, 3, 4, 5, 5], new=array([1, 2, 3, 4, 5]))
Traceback (most recent call last):
  File "/Users/cwebster/src/scratch/observe_array_issue.py", line 21, in <module>
    example.list_or_array = numpy.array([1, 2, 3, 4, 5])
  File "/Users/cwebster/.edm/envs/test-data-view-basics/lib/python3.6/site-packages/traits/observation/_observer_change_notifier.py", line 152, in __call__
    dispatcher=self.dispatcher,
  File "/Users/cwebster/.edm/envs/test-data-view-basics/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py", line 164, in observer_change_handler
    if event.new not in UNOBSERVABLE_VALUES:
```

This is because equality testing for arrays doesn't return `True` or `False`.

The fix here is to use identity testing, since all of the `UNOBSERVABLE_VALUES` are unique values like `None`.  Something like:
```
all(event.new is not value for value in UNOBSERVABLE_VALUES)
```
should work.  A similar change would need to be made on line 71 and 92 of the same file.

**Comment by kitchoi** [comment]
Agreed this is a bug. Alternatively, checking for `isinstance(event.new, IObservable)` should work too.  `CTrait`, `TraitList`, `TraitDict` and `TraitSet` are all registered as `IObservable`.

**Comment by kitchoi** [comment]
> Alternatively, checking for isinstance(event.new, IObservable) should work too. 

Ah, sorry, ignore this. The returned values of these functions/generators are intended to be input of `IObserver.iter_objects`, which are expected to handle anything.  Looks like _is_ comparison as @corranwebster suggested is the right solution.
