### ISSUE TITLE
Skip tests that depend on pkg_resources if pkg_resources not present

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1300]
Currently if the Traits test suite is run in an empty environment (containing only Traits itself), two tests fail when attempting to import `pkg_resources` (which currently comes as part of the `setuptools` distribution). Those tests should be skipped instead if `pkg_resources` is not available.

One day, once Python 3.6 is ancient history, we should be able to replace the `pkg_resources` dependence with dependence on `importlib.resources` from the standard library.

**Comment by mdickinson** [comment]
Here are the test failures:
```
(testing) mdickinson@mirzakhani Desktop % python -m unittest discover traits
........................................................................................................................................................................................................................................................................................................................................................ssssssssssss...s..sss.............................ssssss...............................................................................................................ssssssss............................................ssssssssssssssss...........s.....................................................s.....s..........s...........s.........s.........s.........s..........................................E.......s........s....s....s....s....s....s....s....s..........................................................................................................................................s.........................................s..............................................................................................................................s..........................................................................................................................s...........................sss....................................ssss............................Essssssss.............................ssssss..
======================================================================
ERROR: traits.tests.test_historical_unpickling (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: traits.tests.test_historical_unpickling
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/mdickinson/.venvs/testing/lib/python3.8/site-packages/traits/tests/test_historical_unpickling.py", line 20, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'


======================================================================
ERROR: traits.tests.test_version (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: traits.tests.test_version
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/mdickinson/.venvs/testing/lib/python3.8/site-packages/traits/tests/test_version.py", line 18, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'


----------------------------------------------------------------------
Ran 1374 tests in 21.001s

FAILED (errors=2, skipped=88)
```
