### ISSUE TITLE
Exception occurs when deleting synched trait

### ISSUE THREAD

**Issue by jvkersch** [enthought/traits#131]
The following traceback occurs when the code below is executed:

```
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.A object at 0x10741a
ef0>, trait: t, old value: 0, new value: 42                                                
Traceback (most recent call last):
  File "/Users/jvkersch/Desktop/Enthought Projects/traits/traits/trait_notifiers.py", line 5
20, in _dispatch_change_event                                                              
    self.dispatch( handler, *args )
  File "/Users/jvkersch/Desktop/Enthought Projects/traits/traits/trait_notifiers.py", line 4
83, in dispatch                                                                            
    handler( *args )
  File "/Users/jvkersch/Desktop/Enthought Projects/traits/traits/has_traits.py", line 2680, 
in _sync_trait_modified                                                                    
    for object, object_name in info[ name ].values():
KeyError: 't'
```

``` python
from traits.api import HasTraits, Int

class A(HasTraits):
    t = Int

a = A()
b = A()

a.sync_trait('t', b, mutual=False)

del b

a.t = 42
```

**Comment by stefanoborini** [comment]
I tried to reproduce this but I get no error in '4.7.0.dev45'. I assume it's already fixed.
