### ISSUE TITLE
Tuple validation turns all exceptions into TraitError

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1389]
Currently, validation of a `Tuple` trait type turns all exceptions into `TraitError`. In general, this is undesirable behaviour, since it risks masking genuine programming errors. It should instead propagate exceptions other than `TraitError`.

Nevertheless, changing this would be a backwards incompatible change. We may want to warn (with a `DeprecationWarning`) on exceptions other than `TraitError`, and only propagate those exceptions in Traits 7.0.

**Comment by mdickinson** [comment]
An example of the issue. There's a coding error in the `OddInt` implementation which ought to raise `NameError`, but instead we get an inscrutable `TraitError`:

```python
# Example of Tuple validation swallowing exceptions

from traits.api import BaseInt, HasStrictTraits, Tuple


class OddInt ( BaseInt ):

    # Define the default value
    default_value = 1

    # Describe the trait type
    info_text = 'an odd integer'

    def validate ( self, object, name, value ):
        value = super(OddInt, self).validate(object, name, value)
        if (value % 2) == 1:
            return valeu  # accidental-on-purpose spelling mistake

        self.error( object, name, value )


class A(HasStrictTraits):
    odd_int_pair = Tuple(OddInt(), OddInt())


a = A()
a.odd_int_pair = (3, 5)
```

When this code is run on my machine:
```
(traits) mdickinson@mirzakhani traits % python test.py
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/test.py", line 27, in <module>
    a.odd_int_pair = (3, 5)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'odd_int_pair' trait of an A instance must be a tuple of the form: (an odd integer, an odd integer), but a value of (3, 5) <class 'tuple'> was specified.
```

**Comment by mdickinson** [comment]
In contrast, if we have a simple trait `an_odd_int = OddInt()` on `A`, then we get the following:
```
>>> a.an_odd_int = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/test.py", line 17, in validate
    return valeu
NameError: name 'valeu' is not defined
```

Given this, I'm tempted to view the current behaviour as a bug and fix it for the next release. Code that's accidentally relying on the current behaviour is likely already buggy.
