### ISSUE TITLE
Unittest tools has Instance(threading.Lock) trait definition that doesn't behave as intended.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1408]
The `testing.py` module has this trait definition in the `_TraitsChangeCollector` class:

https://github.com/enthought/traits/blob/cc01cbd6de7ddc2a61514f20c26b18f9d7b6be21/traits/testing/unittest_tools.py#L161

That was presumably intended to say that `_lock` should be a threading `Lock`. But `threading.Lock` is not a type, so this piece of logic kicks in:

https://github.com/enthought/traits/blob/cc01cbd6de7ddc2a61514f20c26b18f9d7b6be21/traits/trait_types.py#L3275-L3276

Which means that the `_lock` trait accepts anything that's a built-in function or method, and nothing else. In particular, it _won't_ accept a lock created using `threading.Lock`:

```python
>>> from traits.api import *
>>> import threading
>>> class A(HasStrictTraits):
...     lock = Instance(threading.Lock, ())
... 
>>> a = A()
>>> a.lock
<unlocked _thread.lock object at 0x1070bf660>
>>> a.lock = threading.Lock()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'lock' trait of an A instance must be a builtin_function_or_method or None, but a value of <unlocked _thread.lock object at 0x107162a80> <class '_thread.lock'> was specified.
```

**Comment by mdickinson** [comment]
Another thing that could be fixed at the same time as this bug: the lock itself is currently instantiated through default-value handling. It's possible that that default value handling could be triggered on two threads simultaneously, and with exactly the right (wrong) timing we could end up with two different locks, which would defeat the point.

It would be safer to allocate the lock in the `__init__` method.
