### ISSUE TITLE
test_enum test failure with Python 3.6.0

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1426]
The Traits test suite fails when run in an environment with Python 3.6.0, TraitsUI, and PyQt5. While the root cause seems to be an issue with Python 3.6.0 in particular, there may be an issue to be solved in TraitsUI - the failure mode here is rather obscure.

Steps to reproduce:
```
mdickinson@mirzakhani Desktop % edm env create testing --force --version 3.6.0 
Removing environment: testing
Fetching indices for runtime repositories. done
Installing runtime... done
Fetching indices for package repositories... done
Installing/removing package(s)
setuptools        [..........................................................................]
mdickinson@mirzakhani Desktop % edm install -e testing traits traitsui pyqt5       
Fetching indices for package repositories... done

The following packages will be installed:

    icu4c                50.2-2     10.69  MiB
    importlib_metadata   2.0.0-1    59     KiB
    importlib_resources  3.3.0-1    58     KiB
    libjpeg              7.0-5     268     KiB
    libpng               1.6.36-5  447     KiB
    libxml2              2.9.7-1     1.38  MiB
    libxslt              1.1.30-1  320     KiB
    pyface               7.2.0-2     2.21  MiB
    pyqt5                5.14.2-3    5.44  MiB
    pyqt5_sip            12.7.2-1   76     KiB
    qt                   5.12.6-7   50.61  MiB
    traits               6.2.0-1     5.35  MiB
    traitsui             7.1.1-3     2.51  MiB
    zipp                 3.4.0-2    10     KiB

Do you want to continue ? [Y/n]: y
Installing/removing package(s)
traitsui            [........................................................................]
mdickinson@mirzakhani Desktop % edm run -e testing -- python -m unittest traits.tests.test_enum.TestGui.test_create_editor 
E
======================================================================
ERROR: test_create_editor (traits.tests.test_enum.TestGui)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/traits/tests/test_enum.py", line 353, in test_create_editor
    with UITester().create_ui(obj):
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/traitsui/testing/tester/ui_tester.py", line 65, in __init__
    self._registries.append(get_default_registry())
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/traitsui/testing/tester/_ui_tester_registry/default_registry.py", line 41, in get_default_registry
    this_package + '.' + toolkit)
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 973, in _gcd_import
  File "<frozen importlib._bootstrap>", line 923, in _sanity_check
SystemError: Parent module 'traitsui.testing.tester._ui_tester_registry.qt4' not loaded, cannot perform relative import

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (errors=1)
```

**Comment by mdickinson** [comment]
https://bugs.python.org/issue30876 looks relevant here

**Comment by mdickinson** [comment]
Okay, this is really either a TraitsUI bug or a Python bug, depending on your point of view. I'm going to close here and open an issue on TraitsUI.
