### ISSUE TITLE
add_trait raises ValueError when watching all traits

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1503]
[Extracted from discussion in #1496]

On my machine, on the main branch, the following script fails, giving `ValueError: Trait named 'child' not found on 'child'.`

```python
from traits.api import HasTraits, Instance, Str
from traits.observation.api import match


class Child(HasTraits):
    name = Str()


class Parent(HasTraits):
    pass


foo = Parent()
foo.observe(print, match(lambda name, trait: True, notify=False).trait("child"))
foo.add_trait("child", Instance(Child))
```

Here's the full traceback:
```python
(traits) mdickinson@mirzakhani traits % python test.py
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/test.py", line 15, in <module>
    foo.add_trait("child", Instance(Child))
  File "/Users/mdickinson/Enthought/ETS/traits/traits/has_traits.py", line 2897, in add_trait
    self.trait_added = name
  File "/Users/mdickinson/Enthought/ETS/traits/traits/observation/_observer_change_notifier.py", line 147, in __call__
    self.observer_handler(
  File "/Users/mdickinson/Enthought/ETS/traits/traits/observation/_has_traits_helpers.py", line 108, in observer_change_handler
    add_or_remove_notifiers(
  File "/Users/mdickinson/Enthought/ETS/traits/traits/observation/_observe.py", line 54, in add_or_remove_notifiers
    callable_()
  File "/Users/mdickinson/Enthought/ETS/traits/traits/observation/_observe.py", line 94, in __call__
    step()
  File "/Users/mdickinson/Enthought/ETS/traits/traits/observation/_observe.py", line 163, in _add_or_remove_notifiers
    for observable in self.graph.node.iter_observables(self.object):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/observation/_named_trait_observer.py", line 87, in iter_observables
    raise ValueError(
ValueError: Trait named 'child' not found on 'child'.
```

**Comment by mdickinson** [comment]
It looks as though `FilteredTraitObserver.get_maintainer` is returning the wrong thing. It's also being called twice with the test script above, for reasons I don't yet understand.

**Comment by mdickinson** [comment]
`trait_added` is a red herring here. The following script is also problematic:

```python
from traits.api import Event, HasTraits, Str
from traits.observation.api import match


class Parent(HasTraits):
    some_event = Event(Str)


parent = Parent()
parent.observe(print, match(lambda name, trait: True, notify=False).trait("name"))
parent.some_event = "whoops"
```

The `on_trait_change` equivalent is more tolerant: the following code runs without errors (and without any output):

```python
from traits.api import Event, HasTraits, Str
from traits.observation.api import match


class Parent(HasTraits):
    some_event = Event(Str)


def print_event(obj, name, old, new): print(object, name, old, new)


parent = Parent()
parent.on_trait_change(print_event, "+:name")
parent.some_event = "whoops"
```

**Comment by mdickinson** [comment]
Closing: this is not a bug - the behaviour is by design. In the original script, the `add_trait` call results in the `trait_added` event being fired. The listener then tries to hook up a listener to "child" on the value of that trait, but that fails because the trait value is a string rather than a `HasTraits` instance.
