### ISSUE TITLE
How to fix --- Exception occurred in traits notification handler issues with PyQt5

### ISSUE THREAD

**Issue by shivak3** [enthought/traits#1606]
~~~
usr/local/lib64/python3.6/site-packages/traits/etsconfig/etsconfig.py:420: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  % (environment_variable, parent_directory)
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.plugins.mayavi_ui_plugin.MayaviUIPlugin object at 0x7f92bbecbaf0>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x7f92bbecbd58>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/traits/trait_notifiers.py", line 654, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/local/lib64/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 498, in handle_simple
    self.next.register(new)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 464, in register
    value = getattr(self, type)(new, name, False)
  File "/usr/local/lib64/python3.6/site-packages/traits/traits_listener.py", line 738, in _register_simple
    return next.register(getattr(object, name))
  File "/usr/local/lib/python3.6/site-packages/envisage/ui/workbench/workbench_application.py", line 140, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/local/lib64/python3.6/site-packages/mayavi/plugins/mayavi_workbench_application.py", line 121, in _splash_screen_default
    show_log_messages = True,
  File "/usr/local/lib/python3.6/site-packages/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the null pyface.ui.null backend doesn't implement splash_screen:SplashScreen
~~~
 Could any one please suggest any help?

**Comment by mdickinson** [comment]
Hi @shivak3. Sorry, but this is the wrong place to ask for help with this - this is likely not a bug with Traits itself. You might try asking on the Enthought Tool Suite users mailing list: https://groups.google.com/g/ets-users .

It'll also be easier for people to provide help if you can provide a script that produces the error, and provide more information about your system, installed packages, and environment variables.
