### ISSUE TITLE
Deprecate acceptance of lists by BaseTuple and Tuple traits

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1626]
Motivated by #1619 

`BaseTuple` and `Tuple` are somewhat inconsistent about when they accept lists, and it's a bit surprising that they ever accept lists:

- `BaseTuple` always accepts lists
- a simple `Tuple()` trait accepts lists, but a trait with types `Tuple(Int(), Str())` does not

```python
>>> from traits.api import *
>>> class A(HasTraits):
...     bt_no_types = BaseTuple()
...     bt = BaseTuple(Int, Str)
...     t_no_types = Tuple()
...     t = Tuple(Int, Str)
... 
>>> a = A()
>>> a.bt_no_types = [2, "2"]
>>> a.bt = [2, "2"]
>>> a.t_no_types = [2, "2"]
>>> a.t = [2, "2"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 't' trait of an A instance must be a tuple of the form: (an integer, a string), but a value of [2, '2'] <class 'list'> was specified.
```

I propose getting rid of the inconsistency and only ever accepting tuples for both `Tuple` and `BaseTuple` traits. This would be a backwards incompatible change, so we'd at least need a deprecation warning period.

**Comment by effigies** [comment]
@mdickinson Is there any way to direct `Tuple` to accept `list` inputs, recursively? Or to subclass `Tuple` to accept lists? The use case I have is JSON (de)serialization of a traited class.

**Comment by mdickinson** [comment]
@effigies Subclassing `BaseTuple` looks like the right thing here. (The fast validation code used by `Tuple` isn't really designed for subclassing.)

Other possible options: to ease transition, we _could_ introduce an `allow_list` keyword argument to the `Tuple` type to explicitly allow lists in all situations (or perhaps `allow_sequence`). Or we could add a `CTuple` ("coercing tuple") trait type similar to the existing `CInt`, `CFloat`, etc.

**Comment by effigies** [comment]
Of the two, CTuple sounds like the more straightforward one to me, consistent with the existing API.

That said, now I figured out how to solve this problem, I don't have a great need for it to be solved upstream. We already have a module of extensions to traits that we'll use, so this isn't going out of our way.

**Comment by mdickinson** [comment]
Agreed; the `allow_list` parameter would really just be a quick fix to provide an easy migration path for those affected by this deprecation. That said, with current resourcing a quick fix may be all we have time for - `CTuple` would be something of a new feature (and would probably need to be matched by things like `CList` for consistency), and that would likely put it out of scope. (That's not to say that there won't _be_ new features in Traits in the future, but it's not something we have resources for in the _near_ future.)
