### ISSUE TITLE
ValueError thrown in TreeEditor with 2-dimension Array 

### ISSUE THREAD

**Issue by yves-surrel** [enthought/traits#1637]
With the following code:

```
import numpy as np
from traits.api import HasTraits, Array, List, self
from traitsui.api import View, Item, TreeEditor, TreeNode

class A(HasTraits):
    a = Array
    
class B(HasTraits):
    content = List
    myself = self
    
    def _content_default(self):
        return [
            A(a=np.arange(4)),
            A(a=np.arange(20).reshape((4, 5)))
            ]
         
tree_editor = TreeEditor(
    nodes=[
        TreeNode(
            node_for=[B],
            children='content',
        ),
        TreeNode(
            node_for=[A],
            children='',
        ),
    ])
    
view = View(Item('myself', editor=tree_editor, show_label=False))

B().configure_traits(view=view)
```
selecting the 2nd leaf with an array of shape (4, 5) throws 4 times (once per line):
```
Traceback (most recent call last):
  File "/Users/yves/miniconda3/lib/python3.8/site-packages/traits/trait_notifiers.py", line 342, in __call__
    self.handler(*args)
  File "/Users/yves/miniconda3/lib/python3.8/site-packages/traitsui/editors/tuple_editor.py", line 195, in _field_changed
    if new != value[index]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by corranwebster** [comment]
The error seems to be coming from `TupleEditor` not `TreeEditor`, which makes me think that the issue is not with the TreeEditor as such.  Try:
- making the `TreeEditor` not `editable`
- adding a TraitsUI `View` for `A` which provides an `ArrayEditor`, `ArrayViewEditor` or similar for the `a` trait
- adding a `view` to the `TreeNode` for `A` which provides an `ArrayEditor`, `ArrayViewEditor` or similar for the `a` trait.

There may be an issue around why `TraitsUI` is choosing a `TupleEditor` for an `Array` trait by default.  I would be curious to know what you get when just viewing an `A` instance outside of the `TreeEditor`.

But also because NumPy arrays have non-standard comparison operators there may well be places where array values cannot be used in TraitsUI without appropriate adaptation.

**Comment by yves-surrel** [comment]
For now, I just patch `TupleEditor` in the following way (I only use numpy arrays):
```
from traitsui.editors.tuple_editor import TupleStructure

def _field_changed(self, name, old, new):
    """ Updates the underlying tuple when any field changes value.
    """
    index = int(name[1:])
    value = self.editor.value
    if (new != value[index]).any(): # <---- added .any()
        self.editor.value = tuple(
            [getattr(self, "f%d" % i) for i in range(self.fields)]
        )
        
TupleStructure._field_changed = _field_changed
```

**Comment by mdickinson** [comment]
I'm going to transfer this issue to the TraitsUI repository - I think it's more appropriate there.
