### ISSUE TITLE
Sphinx 7.2 breaks trait documenter

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1754]
It looks as though recent versions of Sphinx have broken the Traits documenter extension. Our "Test installation from PyPI" job has had recent runs with Sphinx 7.1.2 ([which passed](https://github.com/enthought/traits/actions/runs/5792421358)), and with Sphinx 7.2.2 ([which failed](https://github.com/enthought/traits/actions/runs/5934107116/job/16090496336)).

Here are the test failures:
```python
======================================================================
ERROR: test_abbreviated_annotations (traits.util.tests.test_trait_documenter.TestTraitDocumenter.test_abbreviated_annotations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/traits/util/tests/test_trait_documenter.py", line 147, in test_abbreviated_annotations
    with self.create_directive() as directive:
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/traits/util/tests/test_trait_documenter.py", line 226, in create_directive
    app = SphinxTestApp(srcdir=path(tmpdir))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sphinx/testing/util.py", line 105, in __init__
    outdir.mkdir(parents=True, exist_ok=True)
    ^^^^^^^^^^^^
AttributeError: 'path' object has no attribute 'mkdir'

======================================================================
ERROR: test_can_document_member (traits.util.tests.test_trait_documenter.TestTraitDocumenter.test_can_document_member)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/traits/util/tests/test_trait_documenter.py", line 177, in test_can_document_member
    with self.create_directive() as directive:
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/traits/util/tests/test_trait_documenter.py", line 226, in create_directive
    app = SphinxTestApp(srcdir=path(tmpdir))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/sphinx/testing/util.py", line 105, in __init__
    outdir.mkdir(parents=True, exist_ok=True)
    ^^^^^^^^^^^^
AttributeError: 'path' object has no attribute 'mkdir'

----------------------------------------------------------------------
```

**Comment by mdickinson** [comment]
See also [this job](https://github.com/enthought/traits/actions/runs/6081139610/job/16496235157) with Sphinx 7.2.5, which failed similarly.

**Comment by mdickinson** [comment]
Related, but not quite the same issue: https://github.com/sphinx-doc/sphinx/issues/11605

**Comment by mdickinson** [comment]
It looks as though it's only the test that's broken, not the Trait documenter itself. I've updated the issue title accordingly.
