### ISSUE TITLE
user data tests failing on Jenkins / Windows

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#197]
See [this run](http://jenkins.enthought.com:8080/job/Traits_PR_builder/117/ARCH=x86,label=Windows/console), for example.

```
======================================================================
ERROR: set user data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "traits\etsconfig\tests\test_etsconfig.py", line 173, in test_set_user_data
    old = self.ETSConfig.user_data
  File "traits\etsconfig\etsconfig.py", line 295, in _get_user_data
    self._user_data = self._initialize_user_data()
  File "traits\etsconfig\etsconfig.py", line 451, in _initialize_user_data
    parent_directory = shell.SHGetFolderPath(0, MY_DOCS, 0, 0)
com_error: (-2147024894, 'The system cannot find the file specified.', None, None)

======================================================================
ERROR: user data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "traits\etsconfig\tests\test_etsconfig.py", line 159, in test_user_data
    dirname = self.ETSConfig.user_data
  File "traits\etsconfig\etsconfig.py", line 295, in _get_user_data
    self._user_data = self._initialize_user_data()
  File "traits\etsconfig\etsconfig.py", line 451, in _initialize_user_data
    parent_directory = shell.SHGetFolderPath(0, MY_DOCS, 0, 0)
com_error: (-2147024894, 'The system cannot find the file specified.', None, None)

======================================================================
ERROR: user data is idempotent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "traits\etsconfig\tests\test_etsconfig.py", line 191, in test_user_data_is_idempotent
    self.test_user_data()
  File "traits\etsconfig\tests\test_etsconfig.py", line 159, in test_user_data
    dirname = self.ETSConfig.user_data
  File "traits\etsconfig\etsconfig.py", line 295, in _get_user_data
    self._user_data = self._initialize_user_data()
  File "traits\etsconfig\etsconfig.py", line 451, in _initialize_user_data
    parent_directory = shell.SHGetFolderPath(0, MY_DOCS, 0, 0)
com_error: (-2147024894, 'The system cannot find the file specified.', None, None)

======================================================================
ERROR: write to user data directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "traits\etsconfig\tests\test_etsconfig.py", line 203, in test_write_to_user_data_directory
    dirname = self.ETSConfig.user_data
  File "traits\etsconfig\etsconfig.py", line 295, in _get_user_data
    self._user_data = self._initialize_user_data()
  File "traits\etsconfig\etsconfig.py", line 451, in _initialize_user_data
    parent_directory = shell.SHGetFolderPath(0, MY_DOCS, 0, 0)
com_error: (-2147024894, 'The system cannot find the file specified.', None, None)
```

**Comment by stefanoborini** [comment]
I guess this is not relevant anymore. Closing
