### ISSUE TITLE
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, ... (QT/wx embedding from mayavi broken?)

### ISSUE THREAD

**Issue by jamasi** [enthought/traits#235]
As stated in [mayavi issue 161](https://github.com/enthought/mayavi/issues/161) there seems to be a problem with traits and the new version of mayavi when running the embedding examples from the documentation of mayavi.

I'm not sure on how to debug this any further and if traits(ui) or mayavi or just the example code is at fault here.

**Comment by jamasi** [comment]
Using the qt_embedding.py example from mayavi 4.4.2 docs I still get this:

```
$ python qt_embedding.py 
Traceback (most recent call last):
  File "qt_embedding.py", line 95, in <module>
    mayavi_widget = MayaviQWidget(container)
  File "qt_embedding.py", line 70, in __init__
    kind='subpanel').control
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 1859, in edit_traits
    handler, id, scrollable, args )
  File "/usr/lib64/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 85, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 143, in __init__
    self.control = panel(ui)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 231, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 572, in __init__
    layout = self._add_items(content, inner)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 832, in _add_items
    ui, object, name, item.tooltip, None
  File "/usr/lib64/python2.7/site-packages/traitsui/editor_factory.py", line 140, in simple_editor
    description = description )
  File "/usr/lib64/python2.7/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
  File "/usr/lib64/python2.7/site-packages/traits/trait_types.py", line 2801, in create_default_value
    return klass( *args[1:], **kw )
  File "/usr/lib64/python2.7/site-packages/mayavi/tools/mlab_scene_model.py", line 36, in __init__
    self.engine.new_scene(self)
  File "/usr/lib64/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/mayavi/plugins/envisage_engine.py", line 88, in new_scene
    editor.name = name
  File "/usr/lib64/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'name' trait of a SceneEditor instance must be a unicode string, but a value of <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7fd77f5cddd0> <class 'mayavi.tools.mlab_scene_model.MlabSceneModel'> was specified.
```

I'm using VTK 6.1.0, traits 4.5.0 and traitsui 4.4.0 on a gentoo/sabayon 64bit linux.

is there an easy fix for this?

**Comment by mdickinson** [comment]
Closing as out of date; this was fixed upstream in Mayavi.
