### ISSUE TITLE
Possible reasons for DLL function call conflicting with traits UI?

### ISSUE THREAD

**Issue by ehchen** [enthought/traits#249]
Dear Developers,

It seems calling the PI_EnumerateUSB DLL function conflicts with some functions in my Enthought distribution package "traits". Somehow, by calling PI's DLL function it is affecting the trait attribute "parent, view, context" such that the listener is being wiped out(?). But if I just load the DLL without calling the EnumerateUSB function then traits user interface starts as expected.

I have tried using both cdll and windll to import the 64bit DLL from Physik Instrumente (PI). I have also tried several variations of their DLLs.

More specifically, here are the errors I am seeing:

``` python
2015-07-17 09:08:22,612 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <traits.traits_listener.ListenerParser object at 0x000000000B8B8830>, trait: text, old value: , new value: parent, view, context
Traceback (most recent call last):
File "C:\User\$whoami\AppData\Local\Enthought\Canopy\User\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
self.handler( *args )
File "C:\Users\$whoami\AppData\Local\Enthought\Canopy\User\lib\site-packages\traits\traits_listener.py", line 1302, in _text_changed
self.listener = self.parse()
File "C:\Users\$whoami\AppData\Local\Enthought\Canopy\User\lib\site-packages\traits\traits_listener.py", line 1172, in parse
return self.parse_group( EOS )
File "C:\Users\$whoami\AppData\Local\Enthought\Canopy\User\lib\site-packages\traits\traits_listener.py", line 1191, in parse_group
self.error( "Expected ',' or end of string" )
File "C:\Users\$whoami\AppData\Local\Enthought\Canopy\User\lib\site-packages\traits\traits_listener.py", line 1291, in error
( msg, self.index, self.text ) )
TraitError: Expected ',' or end of string at column 8 of 'parent, view, context'
```

Thanks, Ed

PS: I put a similar post on stack exchange as well:
http://stackoverflow.com/questions/31476890/physik-instrumente-dll-conflict-with-enthought-traits-package

**Comment by mdickinson** [comment]
Hi Ed,

I'm afraid it's difficult to tell what's going on without seeing the code.  Can you cut down your code to a minimal example that demonstrates the issue, and post that minimal example?

**Comment by stefanoborini** [comment]
Could not reproduce and haven't heard back. Closing
