### ISSUE TITLE
Confused pop method in "Either(None, Dict)" trait.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#278]
On a trait that can be either `None` or a dictionary, the `pop` method seems to be generating strange results:

```
Python 2.7.10 |Master 2.1.0.dev1829 (64-bit)| (default, Oct 21 2015, 09:09:19) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = Either(None, Dict)
... 
>>> a = A()
>>> a.foo = {'a': 1, 'bb': 2}
>>> a.foo.pop('a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_handlers.py", line 3180, in pop
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_handlers.py", line 3056, in _send_trait_items_event
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_handlers.py", line 172, in error
traits.trait_errors.TraitError: The 'foo_items' trait of an A instance must be a TraitListEvent or None, but a value of <traits.trait_handlers.TraitDictEvent object at 0x108746850> <class 'traits.trait_handlers.TraitDictEvent'> was specified.
```

**Comment by mdickinson** [comment]
`append` gives similar results

**Comment by mdickinson** [comment]
A similar traceback occurs from the following:
```
from traits.api import Dict, HasStrictTraits, List, Str

class Collection(HasStrictTraits):
    results = Dict(Str, List(Str))

collection = Collection(results={'foo': []})
collection.results['foo'].append('bar')
```

Traceback:
```
Traceback (most recent call last):
  File "traits_bug.py", line 7, in <module>
    collection.results['foo'].append('bar')
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_handlers.py", line 2504, in append
    raise excp
traits.trait_errors.TraitError: Each element of the 'results_items' trait of a Collection instance must be a TraitDictEvent or None, but a value of <traits.trait_handlers.TraitListEvent object at 0x107e6d990> <class 'traits.trait_handlers.TraitListEvent'> was specified.
```
