### ISSUE TITLE
np.bool_ accepted in Bool, but not in Dict(Int, Bool)

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#299]
In the code below, an `np.bool_` instance is accepted in a `Bool` trait (which seems reasonable, and in any case isn't something we can change without breaking backwards compatibility), but not in `Dict(Int, Bool)`. The latter behaviour is surprising.

A more minor issue: after assigning an `np.bool_` to a `Bool` trait, I'd still expect to get a regular Python `bool` out when reading the value of the trait.

```python
Python 2.7.10 |Master 2.1.0.dev1829 (64-bit)| (default, Oct 21 2015, 09:09:19) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import *
>>> class A(HasStrictTraits):
...     foo = Bool
...     bar = Dict(Int, Bool)
... 
>>> a = A()
>>> import numpy as np
>>> x = np.bool_(True)
>>> a.foo = x
>>> type(a.foo)
<type 'numpy.bool_'>
>>> a.bar[1] = x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_handlers.py", line 3113, in __setitem__
traits.trait_errors.TraitError: Each value of the 'bar' trait of an A instance must be a boolean, but a value of True <type 'numpy.bool_'> was specified.
```

**Comment by mdickinson** [comment]
Main issue fixed in #302. Subissue of the `Bool` return type broken out into a separate issue: #304.
