### ISSUE TITLE
traits.api.push_exception_handler(reraise_exceptions=True) fails in Python 3

### ISSUE THREAD

**Issue by cfm** [enthought/traits#321]
[A minimal demonstration](https://gist.github.com/cfm/7375c2a418c8548b0e76f659274f0092) of `traits.api.push_exception_handler(reraise_exceptions=True)` works as expected in Python 2 but not in Python 3:

```
cfm@ozymandias{2}$ source python2/bin/activate
(python2) cfm@ozymandias{3}$ python --version
Python 2.7.10
(python2) cfm@ozymandias{4}$ python reraise_exceptions.py 
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.Foo object at 0x1047db710>, trait: bar, old value: False, new value: True
Traceback (most recent call last):
  File "/Users/cfm/Desktop/reraise_exceptions/python2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "reraise_exceptions.py", line 11, in _bar_changed
    raise Exception('foo changed')
Exception: foo changed
Traceback (most recent call last):
  File "reraise_exceptions.py", line 15, in <module>
    f.bar = True
  File "/Users/cfm/Desktop/reraise_exceptions/python2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 352, in __call__
    handle_exception( object, trait_name, old, new )
  File "/Users/cfm/Desktop/reraise_exceptions/python2/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "reraise_exceptions.py", line 11, in _bar_changed
    raise Exception('foo changed')
Exception: foo changed
(python2) cfm@ozymandias{5:1}$ source python3/bin/activate
(python3) cfm@ozymandias{6}$ python --version
Python 3.5.1
(python3) cfm@ozymandias{7}$ python reraise_exceptions.py 
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.Foo object at 0x10adce308>, trait: bar, old value: False, new value: True
NoneType
Traceback (most recent call last):
  File "reraise_exceptions.py", line 15, in <module>
    f.bar = True
  File "/Users/cfm/Desktop/reraise_exceptions/python3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 352, in __call__
    handle_exception( object, trait_name, old, new )
  File "/Users/cfm/Desktop/reraise_exceptions/python3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 165, in _handle_exception
    raise
RuntimeError: No active exception to reraise
```

**Comment by stefanoborini** [comment]
Cannot reproduce on python 3.5 and the latest traits.

```
(py3) sborini@Mac-34363bd19f52:examples (master)$ python test.py 
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.Foo object at 0x101521af0>, trait: bar, old value: False, new value: True
Traceback (most recent call last):
  File "/Users/sborini/Work/github/simphony/traits/py3/lib/python3.5/site-packages/traits-4.7.0.dev45-py3.5-macosx-10.6-intel.egg/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "test.py", line 12, in _bar_changed
    raise Exception('foo changed')
Exception: foo changed
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    f.bar = True
  File "/Users/sborini/Work/github/simphony/traits/py3/lib/python3.5/site-packages/traits-4.7.0.dev45-py3.5-macosx-10.6-intel.egg/traits/trait_notifiers.py", line 346, in __call__
    handle_exception( object, trait_name, old, new )
  File "/Users/sborini/Work/github/simphony/traits/py3/lib/python3.5/site-packages/traits-4.7.0.dev45-py3.5-macosx-10.6-intel.egg/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "test.py", line 12, in _bar_changed
    raise Exception('foo changed')
Exception: foo changed
(py3) sborini@Mac-34363bd19f52:examples (master)$ python --version
Python 3.5.2
```

**Comment by mdickinson** [comment]
FTR, this was fixed in https://github.com/enthought/traits/pull/266
