### ISSUE TITLE
Travis-ci test build fails on pyhon 2.6

### ISSUE THREAD

**Issue by itziakos** [enthought/traits#344]
I think the issue is related to recent update in shpinx that does not support python 2.6 anymore (and probably the egg in pipy still claims that it is).
```
======================================================================
ERROR: test_get_definition_tokens (traits.util.tests.test_trait_documenter.TestTraitDocumenter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/enthought/traits/traits/util/tests/test_trait_documenter.py", line 40, in test_get_definition_tokens
    from traits.util.trait_documenter import _get_definition_tokens
  File "/home/travis/build/enthought/traits/traits/util/trait_documenter.py", line 16, in <module>
    from sphinx.ext.autodoc import ClassLevelDocumenter
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 29, in <module>
    from sphinx.pycode import ModuleAnalyzer, PycodeError
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sphinx/pycode/__init__.py", line 22, in <module>
    from sphinx.pycode.pgen2 import driver, token, tokenize, parse, literals
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sphinx/pycode/pgen2/driver.py", line 25, in <module>
    from sphinx.pycode.pgen2 import grammar, parse, token, tokenize, pgen
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sphinx/pycode/pgen2/pgen.py", line 7, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
----------------------------------------------------------------------
```

**Comment by mdickinson** [comment]
Closing: this is fixed by #345. See also #348.
