### ISSUE TITLE
TraitError when doing |= on a Set.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#359]
The following appears to be a regression since Traits 4.5.0.

```
(test)bash-3.2$ cat traits_bug.py 
from traits.api import Either, HasTraits, Int, Set, Str

class A(HasTraits):
    maybe_set = Either(Set(Int), None)

a = A(maybe_set = {1, 2, 3})
a.maybe_set |= {4, 5, 6}

(test)bash-3.2$ python traits_bug.py 
Traceback (most recent call last):
  File "traits_bug.py", line 7, in <module>
    a.maybe_set |= {4, 5, 6}
  File "/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/traits/trait_handlers.py", line 2896, in __ior__
    self.update(value)
  File "/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/traits/trait_handlers.py", line 2775, in update
    raise excp
traits.trait_errors.TraitError: Each element of the 'maybe_set_items' trait of an A instance must be a TraitListEvent or None, but a value of <traits.trait_handlers.TraitSetEvent object at 0x101966910> <class 'traits.trait_handlers.TraitSetEvent'> was specified.
```

**Comment by mdickinson** [comment]
This was introduced by #289.

**Comment by mdickinson** [comment]
This is similar to #281.

**Comment by mdickinson** [comment]
Adding to the 6.1.0 milestone; it would be good to get this fixed.

**Comment by kitchoi** [comment]
This is caused by `TraitListEvent` being assumed by `TraitCompound`:
https://github.com/enthought/traits/blob/3e78a41cbf80b4a8f030c49fbb0989ccfea89d3d/traits/trait_handlers.py#L1122-L1130

The error can be avoided by switching to use `Union` instead (released in 6.1):
```
class A(HasTraits):
    maybe_set = Union(Set(Int), None)

a = A(maybe_set = {1, 2, 3})
a.maybe_set |= {4, 5, 6}
```

This is not related to the listeners so I think we can remove the listener rework tag.

**Comment by Kayvan-Zahiri** [comment]
This no longer reproduces. Running the script from the report (`maybe_set = Either(Set(Int), None)`, then `a.maybe_set |= {4, 5, 6}`) against each release:

- 6.0.0, 6.1.0, 6.1.1, 6.2.0, 6.3.0, 6.4.0: `TraitError ... must be a TraitListEvent or None`
- 7.0.0, 7.1.0, 7.2.0: works, set becomes `{1, 2, 3, 4, 5, 6}`

`Set.add`, `Dict.update` and `List.append` inside `Either` also work on 7.2.0, so this looks safe to close as fixed in 7.0.0.

**Comment by mdickinson** [comment]
@Kayvan-Zahiri Agreed! This was fixed as a side-effect of PR #1634. Closing.
