### ISSUE TITLE
Docs don't build on Python 3.6

### ISSUE THREAD

**Issue by jvkersch** [enthought/traits#379]
This is on Python 3.6. Not sure if building the docs is supported on Python 3, but it doesn't look so. Here are the things I tried.

1. The docs try to import mock as a third-party package, it would be better to import it from `unittest` instead on Python 3.

2. When traitsui is not installed, I get a recursion error when the Sphinx config file tries to mock out traitsui (this is while running sphinx-build with `-vT`):
```
13:06 $ make html
sphinx-build -vT -b html -d build/doctrees   source build/html
Running Sphinx v1.5.5

Traceback (most recent call last):
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 122, in <module>
  File "conf.py", line 116, in mock_modules
  File "conf.py", line 116, in <genexpr>
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/unittest/mock.py", line 1825, in __init__
    self._mock_set_magics()  # make magic work for kwargs in init
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/unittest/mock.py", line 1833, in _mock_set_magics
    if getattr(self, "_mock_methods", None) is not None:
  File "conf.py", line 101, in __getattr__
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/unittest/mock.py", line 1825, in __init__
    self._mock_set_magics()  # make magic work for kwargs in init
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/unittest/mock.py", line 1833, in _mock_set_magics
    if getattr(self, "_mock_methods", None) is not None:
  File "conf.py", line 101, in __getattr__
```

3. Installing traitsui to work around the above gives an import error:
```
13:09 $ make html
sphinx-build -vT -b html -d build/doctrees   source build/html
Running Sphinx v1.5.5
Original exception:
Traceback (most recent call last):
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/Users/jvkersch/src/enthought/traits/docs/source/_extensions/refactordoc/__init__.py", line 8, in <module>
    from .function_doc import FunctionDoc
  File "/Users/jvkersch/src/enthought/traits/docs/source/_extensions/refactordoc/function_doc.py", line 10, in <module>
    from base_doc import BaseDoc
ModuleNotFoundError: No module named 'base_doc'


Traceback (most recent call last):
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/Users/jvkersch/src/enthought/traits/docs/source/_extensions/refactordoc/__init__.py", line 8, in <module>
    from .function_doc import FunctionDoc
  File "/Users/jvkersch/src/enthought/traits/docs/source/_extensions/refactordoc/function_doc.py", line 10, in <module>
    from base_doc import BaseDoc
ModuleNotFoundError: No module named 'base_doc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/Users/jvkersch/.edm/envs/edm/lib/python3.6/site-packages/sphinx/application.py", line 516, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension refactordoc (exception: No module named 'base_doc')

Extension error:
Could not import extension refactordoc (exception: No module named 'base_doc')
make: *** [html] Error 1
```

**Comment by corranwebster** [comment]
I don't think any effort has been made into trying to make the docs build on Python 3.

**Comment by rahulporuri** [comment]
I'm not sure when this issue was fixed but ATM i am able to build docs on python 3.6. Closing.
