### ISSUE TITLE
Importing traits fails: No module named ui_traits

### ISSUE THREAD

**Issue by yurivict** [enthought/traits#405]
On FreeBSD, using py27-traits-4.6.0, this code fails:
```
from traits.etsconfig.api import ETSConfig
from traits.api import HasTraits, Instance
from traitsui.api import View, Group, Item
```

```
Traceback (most recent call last):
  File "xx.py", line 5, in <module>
    from traitsui.api import View, Group, Item
  File "/usr/local/lib/python2.7/site-packages/traitsui/api.py", line 27, in <module>
    from .basic_editor_factory import BasicEditorFactory
  File "/usr/local/lib/python2.7/site-packages/traitsui/basic_editor_factory.py", line 30, in <module>
    from .editor_factory import EditorFactory
  File "/usr/local/lib/python2.7/site-packages/traitsui/editor_factory.py", line 34, in <module>
    from .helper import enum_values_changed
  File "/usr/local/lib/python2.7/site-packages/traitsui/helper.py", line 32, in <module>
    from .ui_traits import SequenceTypes
  File "/usr/local/lib/python2.7/site-packages/traitsui/ui_traits.py", line 27, in <module>
    from pyface.ui_traits import (Alignment, Border, HasBorder, HasMargin, Image,
ImportError: No module named ui_traits
```

This code was taken from py-mayavi, which also fails for the same reason.

**Comment by mdickinson** [comment]
Thanks for the report. What versions of `traits`, `traitsui` and `pyface` do you have? This looks like a mismatch between the traitsui version and the pyface version - those two packages are strongly connected, and in general they should always have the same version.

**Comment by mdickinson** [comment]
For comparison, here's what I see on my system:
```
>>> import traits
>>> traits.__version__
'4.6.0'
>>> import traitsui
>>> traitsui.__version__
'6.0.0'
>>> import pyface
>>> pyface.__version__
'6.0.0'
>>> import traitsui.api
>>> import pyface.ui_traits
```

**Comment by yurivict** [comment]
> What versions of traits, traitsui and pyface do you have?

```
py27-pyface-5.1.0              Enthought traits-capable windowing framework
py27-traits-4.6.0_1            Explicitly Typed Attributes for Python
py27-traitsui-6.0.0            Enthought traits-capable user interfaces
```

**Comment by mdickinson** [comment]
Okay, then that's the issue: you need to upgrade your pyface version to 6.0.0.

**Comment by yurivict** [comment]
> Okay, then that's the issue: you need to upgrade your pyface version to 6.0.0.

Yes, that was it!
Thanks!

**Comment by neurosignal** [comment]
I had the same problem..
Just upgraded pyface, and it resolved. Thanks @mdickinson
