### ISSUE TITLE
Test failure in test_numpy_validators_loaded_if_numpy_present

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#441]
A rather strange-looking error seen on an installation of Traits 5.0.0 in a bare EDM Python 3.6 environment, with NumPy 1.16.0 installed via pip:
```
======================================================================
ERROR: test_numpy_validators_loaded_if_numpy_present (traits.tests.test_trait_types.TraitTypesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/traits/tests/test_trait_types.py", line 57, in test_numpy_validators_loaded_if_numpy_present
    import numpy
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/multiarray.py", line 70, in <module>
    def empty_like(prototype, dtype=None, order=None, subok=None):
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/overrides.py", line 240, in decorator
    docs_from_dispatcher=docs_from_dispatcher)(implementation)
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/overrides.py", line 204, in decorator
    add_docstring(implementation, dispatcher.__doc__)
RuntimeError: empty_like method already has a docstring
```

**Comment by mdickinson** [comment]
Here's the root cause. We should probably rewrite the test to be less hacky.
```
Enthought Deployment Manager -- https://www.enthought.com
Python 3.6.0 |Enthought, Inc. (x86_64)| (default, Mar  3 2017, 03:26:01)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import sys
>>> for k in list(sys.modules):
...     if k.startswith("numpy"):
...         del sys.modules[k]
...
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/multiarray.py", line 70, in <module>
    def empty_like(prototype, dtype=None, order=None, subok=None):
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/overrides.py", line 240, in decorator
    docs_from_dispatcher=docs_from_dispatcher)(implementation)
  File "/Users/mdickinson/.edm/envs/testing/lib/python3.6/site-packages/numpy/core/overrides.py", line 204, in decorator
    add_docstring(implementation, dispatcher.__doc__)
RuntimeError: empty_like method already has a docstring
```
