### ISSUE TITLE
Deprecation warnings under Python 3.6 + wxPython 4.0.1 backend running the demo example

### ISSUE THREAD

**Issue by mprogram** [enthought/traits#497]
https://docs.enthought.com/mayavi/mayavi/mlab.html
```
$ env QT_API=pyside2 ETS_TOOLKIT=wx idle-python3.6
14:29:56: Debug: Adding duplicate image handler for 'Windows bitmap file'
14:29:56: Debug: Adding duplicate image handler for 'Windows bitmap file'
14:29:58: Debug: Unsupported OpenGL attribute 32
```
in IDLE:
```
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
======================= RESTART: ~/demo.py =======================

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/clipboard.py", line 25
    PythonObjectFormat = wx.CustomDataFormat('PythonObject')
wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/wx/drag_and_drop.py", line 99
    PythonObject = wx.CustomDataFormat('PythonObject')
wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/action/action_item.py", line 378
    self.control_id, label, bmp, wx.NullBitmap, kind, tooltip, longtip, None
wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/action/action_item.py", line 396
    wx.EVT_TOOL(parent, self.control_id, self._on_tool)
wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/window.py", line 198
    self._position = event.GetEventObject().GetPositionTuple()
wxPyDeprecationWarning: Call to deprecated item. Use GetPosition instead
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/window.py", line 198, in _wx_on_control_move
    self._position = event.GetEventObject().GetPositionTuple()
  File "/usr/lib/python3/dist-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The '_position' trait of a MayaviViewer instance must be a tuple of the form: (a value of class 'int', a value of class 'int'), but a value of wx.Point(900, 730) <class 'wx._core.Point'> was specified.

=============================== RESTART: Shell ===============================
>>> 
```
also enthought/pyface/issues/416

**Comment by mprogram** [comment]
Does the backend matter? I'm getting a **non-tiled** mesh under `ETS_TOOLKIT=qt`, whereas under `wx` it is both, meshed **and** tiled.

**Comment by corranwebster** [comment]
We don't currently support WxPython 4 - there are branches of Pyface and TraitsUI which have support for WxPython 4, but I don't know about the state of Mayavi and WxPython, for example.

You want `env QT_API=pyside2 ETS_TOOLKIT=qt4` instead of `wx` most likely.  Other caveats are that pyside2 support is experimental (PyQt4 and PyQt5 should work just fine) and I also would be cautious about trying to run from inside Idle which uses Tkinter, I think, unless it is starting up your app in a new process.

**Comment by mdickinson** [comment]
I'm going to (attempt to) move this issue to the TraitsUI repository. It's not a Traits issue.

**Comment by mdickinson** [comment]
Issue moved to [enthought/traitsui #579](https://github.com/enthought/traitsui/issues/579) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mprogram** [comment]
@corranwebster, thank you, it is more safe for me to use `ETS_TOOLKIT=qt` (`qt4` is too archaic nowadays:) I belately saw the warnings being related to #288, and also #287 for a similar PR and some discussion.

@mdickinson, just a note: I guessed it is a Traits issue from the last part of a backtrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/window.py", line 198, in _wx_on_control_move
    self._position = event.GetEventObject().GetPositionTuple()
  File "/usr/lib/python3/dist-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The '_position' trait of a MayaviViewer instance must be a tuple of the form: (a value of class 'int', a value of class 'int'), but a value of wx.Point(900, 730) <class 'wx._core.Point'> was specified.

=============================== RESTART: Shell ===============================
>>> 
```

**Comment by corranwebster** [comment]
@mprogram `ETS_TOOLKIT=qt4` will give you either Qt4 or Qt5 depending on which is installed or selected via `QT_API`.  The "qt4" is a reference to the name of the package inside ETS and should have no further consequences.  `ETS_TOOLKIT=qt` will eventually work, but not all parts of ETS have been converted.

So strong advice for now is that you should doe `ETS_TOLLKIT=qt4`.  Despite the name it does what you want.

**Comment by mdickinson** [comment]
@corranwebster Please can you move the above comment to the traitsui issue?

**Comment by mprogram** [comment]
Thank you both for you attention to the reported issue. If that matters, the above edits refer to `qt-at-spi (= 0.4.0-9)` and `libgtk-3-0 (= 3.24.8-1ubuntu1)` under Ubuntu; see them on: https://packages.ubuntu.com/src:qt-at-spi and https://packages.ubuntu.com/src:gtk+3.0 reaspectively

_(a copy here posted to the traitsui issue)_

**Comment by mprogram** [comment]
_(sorry, it's my last copy posted to the traitsui issue, since the original use of `qt4` was first suggested here)_ 

@corranwebster, FYI:
there is a certain difference actually not allowing me to use `qt4` over `qt` under python3 (latest sources): 
```
$ env QT_API=pyqt ETS_TOOLKIT=qt4 mayavi2 ~/demo.py

Traceback (most recent call last):
  File "/usr/bin/mayavi2-3.6", line 11, in <module>
    load_entry_point('mayavi==4.7.1.dev0', 'gui_scripts', 'mayavi2')()
  File "/usr/lib/python3/dist-packages/mayavi/scripts/mayavi2.py", line 602, in main
    mayavi.main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/mayavi/plugins/app.py", line 195, in main
    app.run()
  File "/usr/lib/python3/dist-packages/mayavi/plugins/mayavi_workbench_application.py", line 81, in run
    window.open()
  File "/usr/lib/python3/dist-packages/pyface/workbench/workbench_window.py", line 144, in open
    self._create()
  File "/usr/lib/python3/dist-packages/pyface/ui/qt4/application_window.py", line 130, in _create
    contents = self._create_contents(self.control)
  File "/usr/lib/python3/dist-packages/pyface/workbench/workbench_window.py", line 229, in _create_contents
    self._restore_contents()
  File "/usr/lib/python3/dist-packages/pyface/workbench/workbench_window.py", line 812, in _restore_contents
    self.layout.set_toolkit_memento(self._memento)
  File "/usr/lib/python3/dist-packages/pyface/ui/qt4/workbench/workbench_window_layout.py", line 299, in set_toolkit_memento
    self.window.control.restoreGeometry(geometry)
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'PySide2.QtCore.QByteArray'
```
_compare:_
```
$ env QT_API=pyqt5 ETS_TOOLKIT=qt mayavi2 ~/demo.py

Exception occurred in traits notification handler for object: <mayavi.filters.poly_data_normals.PolyDataNormals object at 0x7f3b70a68f10>, trait: name, old value: PolyDataNormals, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 139893325684232
ERROR|2019-07-06 22:55:26,154|Exception occurred in traits notification handler for object: <mayavi.filters.poly_data_normals.PolyDataNormals object at 0x7f3b70a68f10>, trait: name, old value: PolyDataNormals, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 139893325684232
Exception occurred in traits notification handler for object: <mayavi.modules.surface.Surface object at 0x7f3b708cc410>, trait: name, old value: Surface, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 139893325684232
ERROR|2019-07-06 22:55:26,183|Exception occurred in traits notification handler for object: <mayavi.modules.surface.Surface object at 0x7f3b708cc410>, trait: name, old value: Surface, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 139893325684232
```
It actually runs well despite `KeyError`'s which is a fallout of enthought/mayavi/issues/797 I guess, but it doen't do so well with `qt4`.
