### ISSUE TITLE
Property with lambdas fails in Cython code.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#554]
The following code works in regular Python, but fails under Cython, giving an AttributeError:
```
from traits.api import HasTraits, Str, Property


def Alias(name):
    return Property(
        lambda obj: getattr(obj, name),
        lambda obj, value: setattr(obj, name, value)
    )


class Test(HasTraits):
    name = Str

    funky_name = Alias('name')


print(Test())
```

Under regular Python (3.6), this gives:
```
<__main__.Test object at 0x7fbc381f86d0>
```

Under Cython, we get the following traceback:
```
======================================================================
ERROR: test_on_trait_lambda_failure (traits.tests.test_cythonized_traits.CythonizedTraitsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_cythonized_traits.py", line 218, in test_on_trait_lambda_failure
    self.execute(code)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_cythonized_traits.py", line 228, in execute
    language_level="3",
  File "/Users/mdickinson/.edm/envs/traits-test-3.6/lib/python3.6/site-packages/Cython/Shadow.py", line 133, in inline
    return _cython_inline(f, *args, **kwds)
  File "/Users/mdickinson/.edm/envs/traits-test-3.6/lib/python3.6/site-packages/Cython/Build/Inline.py", line 256, in cython_inline
    return module.__invoke(*arg_list)
  File "_cython_inline_3ddde307201c602bf2c4f8655e393982.pyx", line 16, in _cython_inline_3ddde307201c602bf2c4f8655e393982.__invoke
  File "_cython_inline_3ddde307201c602bf2c4f8655e393982.pyx", line 8, in _cython_inline_3ddde307201c602bf2c4f8655e393982.__invoke.Alias
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 655, in __call__
    return self.maker_function(*args, **metadata)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 1337, in Property
    fget, _arg_count(fget), fset, _arg_count(fset), fvalidate, n
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_handlers.py", line 141, in _arg_count
    return func.__code__.co_argcount
AttributeError: 'NoneType' object has no attribute 'co_argcount'
```

**Comment by mdickinson** [comment]
This still fails, but I now see a different traceback and exception:
```
======================================================================
ERROR: test_property_with_lambdas (traits.tests.test_cythonized_traits.CythonizedTraitsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_cythonized_traits.py", line 172, in test_property_with_lambdas
    obj = self.execute(code)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_cythonized_traits.py", line 233, in execute
    return cython.inline(
  File "/Users/mdickinson/.venvs/traits/lib/python3.8/site-packages/Cython/Shadow.py", line 135, in inline
    return _cython_inline(f, *args, **kwds)
  File "/Users/mdickinson/.venvs/traits/lib/python3.8/site-packages/Cython/Build/Inline.py", line 271, in cython_inline
    return module.__invoke(*arg_list)
  File "_cython_inline_ee7a9872fcbc7a60fb382f51d3c975577ab6509f.pyx", line 19, in _cython_inline_ee7a9872fcbc7a60fb382f51d3c975577ab6509f.__invoke
  File "_cython_inline_ee7a9872fcbc7a60fb382f51d3c975577ab6509f.pyx", line 10, in _cython_inline_ee7a9872fcbc7a60fb382f51d3c975577ab6509f.__invoke.Alias
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_factory.py", line 40, in __call__
    return self.maker_function(*args, **metadata)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 627, in Property
    trait.property_fields = (fget, fset, fvalidate)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/ctrait.py", line 139, in property_fields
    sig = inspect.signature(arg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 2296, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 2107, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <cyfunction __invoke.<locals>.Alias.<locals>.<lambda> at 0x129c5fee0>
```

This Cython issue may be related: https://github.com/cython/cython/issues/2983

**Comment by mdickinson** [comment]
I'm going to close this; it's a Cython bug, not a Traits one.
