### ISSUE TITLE
Cython tests fail on Python 2.7 / Windows

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#557]
The tests in `test_cythonized_traits` currently fail in CI on the specific combination of Python 2.7 / Windows. They pass on Python 3.5 and Python 3.6 on Windows, and for all three Python versions tested for macOS and Linux. The test appears to be a problem with finding the relevant compiler; it's surprising that the CI happily compiles Traits itself (which involves a C extension), but that the configuration fails when compiling C extensions arising from `cython.inline`.

Test failures resemble the following (see [this comment](https://github.com/enthought/traits/pull/555#issuecomment-553359970) in #555 for the full list):
```
======================================================================
ERROR: test_basic_events (traits.tests.test_cythonized_traits.CythonizedTraitsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\site-packages\traits\tests\test_cythonized_traits.py", line 49, in test_basic_events
    obj = self.execute(code)
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\site-packages\traits\tests\test_cythonized_traits.py", line 205, in execute
    language_level="3",
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\site-packages\Cython\Shadow.py", line 133, in inline
    return _cython_inline(f, *args, **kwds)
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\site-packages\Cython\Build\Inline.py", line 250, in cython_inline
    build_extension.run()
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Users\appveyor\.edm\envs\traits-test-2.7\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: [u'path']
```

Possibly the difference is due to using `setuptools` for `ctraits.c` versus `distutils` for the Cython extensions, or perhaps there are differences in the environment variables present for the compilation of the `ctraits` extension versus the compilation of the Cython extensions. I was unable to find a remedy within 30 minutes, and given the diminishing importance of Python 2.7, this issue may never get solved, but it's still worth recording.

**Comment by corranwebster** [comment]
Closing - Python 2.7 no longer supported.
