### ISSUE TITLE
Consider removing the HasTraits.trait_monitor method

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#569]
There's a little-used method on `HasTraits` called `trait_monitor`, that allows arbitrary callbacks to be called on instantiation of a particular `HasTraits` subclass:

```
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = Int
... 
>>> def handler(*args, **kwargs):
...     print("handler called")
...     print("args: ", args)
...     print("kwargs: ", kwargs)
... 
>>> A.trait_monitor(handler)
>>> a = A()
handler called
args:  (<__main__.A object at 0x7ff6d825cd00>,)
kwargs:  {}
```

However:

- this method is unused elsewhere, as far as I'm able to tell
- it's neither documented nor tested
- it's implemented via a piece of global state that keeps track of all current monitors
- it's currently broken: an attempt to use `remove=True` fails with a `ValueError`:

```
>>> A.trait_monitor(handler, remove=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/tt/lib/python3.6/site-packages/traits/has_traits.py", line 1198, in trait_monitor
    index = _trait_monitor_index(cls, handler)
  File "/Users/mdickinson/.edm/envs/tt/lib/python3.6/site-packages/traits/has_traits.py", line 893, in _trait_monitor_index
    for i, _cls, _handler in enumerate(_HasTraits_monitors):
ValueError: not enough values to unpack (expected 3, got 2)
```

Given all that, and given that we have limited resources and many more useful things to focus on, I'd suggest that we remove this method and the associated machinery.

**Comment by mdickinson** [comment]
Update: it's not just removal that's broken: any second call to `trait_monitor` fails. That breakage isn't new, either: the code has been non-functional for over 13 years: https://github.com/enthought/traits/blob/e9a6387e82aba6ea9b83e1a284b6d6d032b4f331/enthought/traits/has_traits.py#L919

That settles it, IMO: it's going.
