### ISSUE TITLE
Documentation build is broken

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#628]
`python etstool.py docs` fails with a traceback:
```
mirzakhani:traits mdickinson$ python etstool.py docs
[EXECUTING] /usr/local/bin/edm run -e traits-test-3.6 -- sphinx-build -b html -d build/doctrees source build/html
Running Sphinx v1.8.5

Exception occurred:
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 1146, in as_ctrait
    trait.set_default_value(self.default_value_type, self.default_value)
TypeError: 'NoneType' object is not callable
The full traceback has been saved in /var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/sphinx-err-tmlmae8t.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command '['/usr/local/bin/edm', 'run', '-e', 'traits-test-3.6', '--', 'sphinx-build', '-b', 'html', '-d', 'build/doctrees', 'source', 'build/html']' returned non-zero exit status 2.
```

Contents of the log:
```
mirzakhani:traits mdickinson$ cat /var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/sphinx-err-tmlmae8t.log
# Sphinx version: 1.8.5
# Python version: 3.6.5 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/mdickinson/.edm/envs/traits-test-3.6/lib/python3.6/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Users/mdickinson/.edm/envs/traits-test-3.6/lib/python3.6/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/Users/mdickinson/.edm/envs/traits-test-3.6/lib/python3.6/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/Users/mdickinson/.edm/envs/traits-test-3.6/lib/python3.6/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/Users/mdickinson/Enthought/ETS/traits/traits/util/trait_documenter.py", line 21, in <module>
    from ..has_traits import MetaHasTraits
  File "/Users/mdickinson/Enthought/ETS/traits/traits/has_traits.py", line 57, in <module>
    from .trait_types import Any, Bool, Disallow, Event, Python
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_types.py", line 3716, in <module>
    ListInt = List(int)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_types.py", line 2427, in __init__
    self.item_trait = trait_from(trait)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 758, in trait_from
    return Trait(something)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 912, in Trait
    return _TraitMaker(*value_type, **metadata).as_ctrait()
  File "/Users/mdickinson/Enthought/ETS/traits/traits/traits.py", line 1146, in as_ctrait
    trait.set_default_value(self.default_value_type, self.default_value)
TypeError: 'NoneType' object is not callable
```

**Comment by mdickinson** [comment]
I can't reproduce after rebuilding my development environment. Closing.
