### ISSUE TITLE
on_trait_change decorator raises exception for embedded trait

### ISSUE THREAD

**Issue by cfarrow** [enthought/traits#7]
This is in traits 3.

I'm using the on_traits_change decorator to respond to changes in     'trace_plot.plot.components.index_mapper.range+'
trace_plot is an instance of a direct subclass of HasTraits,
plot is an instance of VPlotContainer,
components is a LinePlot,
index_mapper and range are the standard for LinePlot.

When the class with using the on_traits_change decorator is instantiated, the following exception is raised:

Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <zoom_plot.ZoomPlot object at 0x24299bd0>, trait: plot, old value: <uninitialized>, new value: <enthought.chaco.plot_containers.VPlotContainer object at 0x242e60f0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/enthought/traits/trait_notifiers.py", line 610, in rebind_call_4
    object, trait_name, old, new )
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/enthought/traits/trait_notifiers.py", line 448, in dispatch
    handler( *args )
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/enthought/traits/traits_listener.py", line 467, in handle_simple
    self.next.register( new )
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/enthought/traits/traits_listener.py", line 433, in register
    value = getattr( self, type )( new, name, False )
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/enthought/traits/traits_listener.py", line 666, in _register_simple
    return next.register( getattr( object, name ) )
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/enthought/traits/traits_listener.py", line 344, in register
    if (new is None) or (new is Undefined) or (new in self.active):
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/weakref.py", line 298, in __contains__
    return wr in self.data
TypeError: unhashable type: 'TraitListObject'

See a71c93750d82ec267bee3dc1aaee3a164c6a4d86 of ripe project - _update_line method.

**Comment by mdickinson** [comment]
This issue isn't actionable without code to reproduce. Unless by some chance @cfarrow still has that code around, let's close this. (@cfarrow: if you _do_ have that code around, or if you disagree with the closing, feel free to re-open).
