### ISSUE TITLE
Unexpected validation failure when using Callable with Either

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#793]
The tests fail when I expected them to pass:
```
from functools import partial

import unittest

from traits.api import Callable, Either, HasRequiredTraits


def dummy(x):
    pass


class Foo(HasRequiredTraits):

    function = Callable()

    function_or_none = Either(None, Callable())


class TestCallable(unittest.TestCase):

    def test_none(self):
        foo = Foo()
        foo.function = None
        foo.function_or_none = None

    def test_partial_function(self):
        foo = Foo()
        foo.function = partial(dummy)
        foo.function_or_none = partial(dummy)


if __name__ == "__main__":
    unittest.main()
```

with results:
```
======================================================================
ERROR: test_none (__main__.TestCallable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "callable_example.py", line 24, in test_none
    foo.function_or_none = None
  File "/Users/kchoi/ETS/traits/traits/base_trait_handler.py", line 77, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'function_or_none' trait of a Foo instance must be a callable value or None, but a value of None <class 'NoneType'> was specified.

======================================================================
ERROR: test_partial_function (__main__.TestCallable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "callable_example.py", line 29, in test_partial_function
    foo.function_or_none = partial(dummy)
  File "/Users/kchoi/ETS/traits/traits/base_trait_handler.py", line 77, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'function_or_none' trait of a Foo instance must be a callable value or None, but a value of functools.partial(<function dummy at 0x10805a8c8>) <class 'functools.partial'> was specified.
```

**Comment by corranwebster** [comment]
Orthogonal comment, but `Callable` already accepts `None` as a valid value.

**Comment by kitchoi** [comment]
Definitely related to #767.  If I remove `fast_validate` on `Callable` then the tests pass.

**Comment by mdickinson** [comment]
`validate_trait_complex` is missing a case for validation type `22`. I should have spotted this in the initial review. Sorry.

**Comment by mdickinson** [comment]
i.e., there should be a `case 22:` block here: https://github.com/enthought/traits/blob/63e3339ba13e674f2edd8e1b2aeb8e5a8e83d8c9/traits/ctraits.c#L3841

**Comment by mdickinson** [comment]
> but `Callable` already accepts `None` as a valid value.

See #773.

**Comment by mdickinson** [comment]
Will put together a quick fix.
