### ISSUE TITLE
TraitListObject __setitem__ does not support iterable as values

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#963]
This test fails:
```
    def test_setitem_with_iterable(self):

        f = Foo(l=["a", "b", "c", "d"])

        python_list = ["a", "b", "c", "d"]
        python_list[::2] = ("a" for _ in range(2))
        f.l[::2] = ("a" for _ in range(2))

        self.assertEqual(f.l, python_list)
```

```
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/traits/traits/tests/test_list.py", line 389, in test_setitem_with_iterable
    f.l[::2] = ("a" for _ in range(2))
  File "/Users/kchoi/Work/ETS/traits/traits/trait_list_object.py", line 166, in __setitem__
    delta = len(values) - slice_len
TypeError: object of type 'generator' has no len()
```

**Comment by mdickinson** [comment]
Still an issue on master. Should be fixed by #969, but #969 currently lacks a regression test for this case.

**Comment by mdickinson** [comment]
#989 now has a regression test for this: https://github.com/enthought/traits/blob/f7798472b7032a0d9c883fd2c07c80041832f879/traits/tests/test_trait_list_object.py#L863-L866

**Comment by kitchoi** [comment]
Closing via #989
