### ISSUE TITLE
TraitList: Assigning generator to slice fails

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#979]
Behaviour on current master:
```
Python 3.8.2 (default, Feb 27 2020, 19:56:42) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = List(Int)
... 
>>> a = A()
>>> a.foo = [1, 2, 3]
>>> a.foo[:] = (x**2 for x in range(5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 279, in __setitem__
    if len(removed) != len(value) and index.step not in {1, None}:
TypeError: object of type 'generator' has no len()
```

The same behaviour is present on Traits 6.0.0 and Traits 5.2.0, so this isn't a (recent) regression. But it differs from the plain-old list behaviour, and I think we should fix it for 6.1.0:

```
>>> foo = [1, 2, 3]
>>> foo[:] = (x**2 for x in range(5))
>>> foo
[0, 1, 4, 9, 16]
```

**Comment by midhun-pm** [comment]
Verified that this issue has been fixed in master.
