### ISSUE TITLE
TraitDictObject setdefault fails if the key is transformed

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#986]
Consider this:
```
>>> from traits.api import CStr, Dict, HasTraits
>>> 
>>> class Foo(HasTraits):
...     a = Dict(CStr)   # cast to string
... 
>>> foo = Foo(a={})
>>> foo.a.setdefault(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/traits/traits/trait_dict_object.py", line 240, in setdefault
    result = self[key]
KeyError: 1
```

Despite the error, the dict is modifed:
```
>>> foo.a
{"1": 2}
```
This behaviour exists in (at least) Traits 5.2.0 and 6.0.0.

I believe this will be fixed as part of #913, but I am opening this issue anyway this can be tracked.

**Comment by mdickinson** [comment]
Adding to the milestone

**Comment by mdickinson** [comment]
See also #1020.

**Comment by mdickinson** [comment]
#913 is now in, and I think we can close this. Here's the current behaviour on master:

```python
Python 3.8.2 (default, Feb 27 2020, 19:56:42) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import CStr, Dict, HasTraits
>>> class Foo(HasTraits):
...     a = Dict(CStr)
... 
>>> foo = Foo(a={})
>>> foo.a.setdefault(1, 2)
2
>>> foo.a
{'1': 2}
```
